// 用于定义 redux 的action类型 必须全局位置，
// 例如  模块名_XXXXX_XXXX
// 如果是异步操作 ，由于用了第三方的一个包，所以必须定义四个type类型,有三个类型必须后面跟上 _pending / _FULFILLED /_REJECTED
// 异步登录
// export const LOGIN = "LOGIN"
// export const LOGIN_PENDING = "LOGIN_PENDING"
// export const LOGIN_FULFILLED = "LOGIN_FULFILLED"
// export const LOGIN_REJECTED = "LOGIN_REJECTED"

export const ADD = "ADD" // 增加数字
export const DEL = "DEL" // 减数

export const LOGIN = "LOGIN" // 异步登录
export const LOGIN_PENDING = "LOGIN_PENDING"
export const LOGIN_FULFILLED = "LOGIN_FULFILLED"
export const LOGIN_REJECTED = "LOGIN_REJECTED"


export const ENTERRISK_GET_ENTERRISKTABLE_LIST = "ENTERRISK_GET_ENTERRISKTABLE_LIST"  // 获取风险预警列表
export const ENTERRISK_GET_ENTERRISKTABLE_LIST_PENDING = "ENTERRISK_GET_ENTERRISKTABLE_LIST_PENDING"
export const ENTERRISK_GET_ENTERRISKTABLE_LIST_FULFILLED = "ENTERRISK_GET_ENTERRISKTABLE_LIST_FULFILLED"
export const ENTERRISK_GET_ENTERRISKTABLE_LIST_REJECTED = "ENTERRISK_GET_ENTERRISKTABLE_LIST_REJECTED"
export const ENTERRISK_UPDATE_SEARCHDATA = "ENTERRISK_UPDATE_SEARCHDATA" // 更新搜索的参数
export const ENTERRISK_GET_BUSINESSLINE_BYUSER = "ENTERRISK_GET_BUSINESSLINE_BYUSER" // 根据用户获取业务条线
export const ENTERRISK_GET_BUSINESSLINE_BYUSER_PENDING = "ENTERRISK_GET_BUSINESSLINE_BYUSER_PENDING" // 根据用户获取业务条线
export const ENTERRISK_GET_BUSINESSLINE_BYUSER_FULFILLED = "ENTERRISK_GET_BUSINESSLINE_BYUSER_FULFILLED" // 根据用户获取业务条线
export const ENTERRISK_GET_BUSINESSLINE_BYUSER_REJECTED = "ENTERRISK_GET_BUSINESSLINE_BYUSER_REJECTED" // 根据用户获取业务条线
export const ENTERRISK_GET_OBJINFOBYID = "ENTERRISK_GET_OBJINFOBYID"  // 根据id获取详情信息
export const ENTERRISK_GET_OBJINFOBYID_PENDING = "ENTERRISK_GET_OBJINFOBYID_PENDING"
export const ENTERRISK_GET_OBJINFOBYID_FULFILLED = "ENTERRISK_GET_OBJINFOBYID_FULFILLED"
export const ENTERRISK_GET_OBJINFOBYID_REJECTED = "ENTERRISK_GET_OBJINFOBYID_REJECTED"

export const ENTERRISK_GET_TYPES_LIST = "ENTERRISK_GET_TYPES_LIST" // 获取决策结果
export const ENTERRISK_GET_TYPES_LIST_PENDING = "ENTERRISK_GET_TYPES_LIST_PENDING" // 获取决策结果
export const ENTERRISK_GET_TYPES_LIST_FULFILLED = "ENTERRISK_GET_TYPES_LIST_FULFILLED" // 获取决策结果
export const ENTERRISK_GET_TYPES_LIST_REJECTED = "ENTERRISK_GET_TYPES_LIST_REJECTED" // 获取决策结果

// 下载
export const ENTERRISK_GET_EXPORT = "ENTERRISK_GET_EXPORT" // 
export const ENTERRISK_GET_EXPORT_PENDING = "ENTERRISK_GET_EXPORT_PENDING" // 
export const ENTERRISK_GET_EXPORT_FULFILLED = "ENTERRISK_GET_EXPORT_FULFILLED" // 
export const ENTERRISK_GET_EXPORT_REJECTED = "ENTERRISK_GET_EXPORT_REJECTED" // 

